# Generated by Django 5.2.3 on 2025-07-23 18:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_usuario_managers'),
    ]

    operations = [
        migrations.CreateModel(
            name='CarritoItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.PositiveIntegerField(default=1)),
                ('agregado_en', models.DateTimeField(auto_now_add=True)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='carrito_items', to='api.cliente')),
                ('oferta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.oferta')),
            ],
            options={
                'unique_together': {('cliente', 'oferta')},
            },
        ),
    ]
