# Generated by Django 5.2.3 on 2025-07-24 00:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_solicitudproducto'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='agricultor',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='productos', to='api.agricultor'),
            preserve_default=False,
        ),
    ]
