# Generated by Django 5.2.3 on 2025-07-25 00:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_producto_agricultor'),
    ]

    operations = [
        migrations.CreateModel(
            name='RespuestaSolicitud',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mensaje', models.TextField()),
                ('fecha_respuesta', models.DateTimeField(auto_now_add=True)),
                ('agricultor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.agricultor')),
                ('solicitud', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='respuestas', to='api.solicitudproducto')),
            ],
        ),
    ]
