# Generated by Django 5.2.3 on 2025-07-25 01:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_respuestasolicitud'),
    ]

    operations = [
        migrations.CreateModel(
            name='NotificacionAgricultor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mensaje', models.TextField()),
                ('leido', models.BooleanField(default=False)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('agricultor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notificaciones', to='api.agricultor')),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.cliente')),
                ('oferta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.oferta')),
            ],
        ),
    ]
